sonar.organization=tripleaze
sonar.projectKey=tripleaze
sonar.projectName=Production-Grade-Cloud-Native-DevOps-Platform

# Path to the source code
sonar.sources=.

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/*.tf, **/*.yaml, **/*.yml, **/*.md, infra/**
