apiVersion: v1
kind: Service
metadata:
  name: chat-db
spec:
  selector:
    app: chat-db
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  externalTrafficPolicy: "Local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-db
    spec:
      containers:
        - name: chat-db
          image: chat-db:latest
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: CONFIGMAP_FILE
              value: "/usr/share/microservice/config.yaml"
          volumeMounts:
            - mountPath: /usr/share/microservice
              name: ms-config-volume
      volumes:
        - name: ms-config-volume
          configMap:
            name: chat-db-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-db-configmap
data:
  # When the config map is mounted as a volume, these will be created as files.
  config.yaml: |-
    ms:
      DEBUG: false
      TESTING: false
      APP_NAME: chat_db
      APPLICATION_ROOT : /
      SQLALCHEMY_TRACK_MODIFICATIONS: true
      SECRET_KEY: "gjr39dkjn344_!67#"
      DATABASE: db.sqlite3
      SQLALCHEMY_DATABASE_URI: sqlite:////microservice/database/db.sqlite3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-db-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chat-db
            port:
              number: 5000