version: '3.8'

services:
  chat-db:
    build:
      context: ./chat_db
    container_name: chat-db
    ports:
      - "8081:8080"
    networks:
      - chat-net

  chat-svc:
    build:
      context: ./chat_svc
    container_name: chat-svc
    ports:
      - "8082:8080"
    networks:
      - chat-net
    depends_on:
      - chat-db
    

  chat-front:
    build:
      context: ./chat_front
    container_name: chat-front
    ports:
      - "8080:8080"
    networks:
      - chat-net
    depends_on:
      - chat-svc

networks:
  chat-net:
    driver: bridge
